# Generated by Django 5.2.3 on 2026-04-10 03:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('study_start_time', models.TimeField(blank=True, help_text='Default study session start time', null=True)),
                ('study_end_time', models.TimeField(blank=True, help_text='Default study session end time', null=True)),
                ('pomodoro_enabled', models.BooleanField(default=False)),
                ('pomodoro_focus_minutes', models.PositiveIntegerField(default=25)),
                ('pomodoro_break_minutes', models.PositiveIntegerField(default=5)),
                ('daily_goal', models.CharField(blank=True, help_text='Daily study goal description', max_length=255)),
                ('distraction_list', models.TextField(blank=True, help_text='List of common distractions (one per line)')),
                ('warning_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('distraction_name', models.CharField(max_length=255)),
                ('distraction_type', models.CharField(choices=[('social_media', 'Social Media'), ('notification', 'Notification'), ('environment', 'Environment'), ('thought', 'Intrusive Thought'), ('physical', 'Physical Need'), ('other', 'Other')], default='other', max_length=20)),
                ('blocked_during_focus', models.BooleanField(default=False, help_text='Was the distraction blocked during focus period')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distraction_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distraction Record',
                'verbose_name_plural': 'Distraction Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_distra_user_id_3efe71_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reaction_score', models.FloatField(blank=True, help_text='Reaction time based score (0-100)', null=True)),
                ('eye_score', models.FloatField(blank=True, help_text='Eye tracking based score (0-100)', null=True)),
                ('hrv_score', models.FloatField(blank=True, help_text='Heart rate variability score (0-100)', null=True)),
                ('final_score', models.FloatField(blank=True, help_text='Combined final drift score (0-100, higher = more drift)', null=True)),
                ('cognitive_state', models.CharField(choices=[('focused', 'Focused'), ('mild_drift', 'Mild Drift'), ('moderate_drift', 'Moderate Drift'), ('severe_drift', 'Severe Drift')], default='focused', max_length=20)),
                ('warning_level', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('reaction_triggered', models.BooleanField(default=False, help_text='Whether reaction test was triggered')),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence (0-1)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drift Record',
                'verbose_name_plural': 'Drift Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_driftr_user_id_67f73e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EyeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('blink_rate', models.FloatField(help_text='Blinks per minute')),
                ('blink_duration', models.FloatField(help_text='Average blink duration in milliseconds')),
                ('eye_state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('drowsy', 'Drowsy'), ('looking_away', 'Looking Away')], default='open', max_length=20)),
                ('eye_score', models.FloatField(help_text='Computed eye fatigue/drowsiness score (0-100)')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eye Record',
                'verbose_name_plural': 'Eye Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_eyerec_user_id_c44139_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal_title', models.CharField(max_length=255)),
                ('target_value', models.FloatField(help_text='Target value (e.g., study hours, tasks)')),
                ('achieved_value', models.FloatField(default=0)),
                ('completion_percent', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal Record',
                'verbose_name_plural': 'Goal Records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='core_goalre_user_id_b0a53b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HRVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bpm', models.FloatField(help_text='Heart rate in beats per minute')),
                ('sdnn', models.FloatField(help_text='SDNN - Standard deviation of NN intervals (ms)')),
                ('stress_level', models.CharField(choices=[('relaxed', 'Relaxed'), ('normal', 'Normal'), ('mild_stress', 'Mild Stress'), ('moderate_stress', 'Moderate Stress'), ('high_stress', 'High Stress')], default='normal', max_length=20)),
                ('hrv_score', models.FloatField(help_text='Computed HRV-based stress/fatigue score (0-100)')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrv_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HRV Record',
                'verbose_name_plural': 'HRV Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_hrvrec_user_id_bb1bac_idx')],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('focus_minutes', models.PositiveIntegerField(default=25)),
                ('break_minutes', models.PositiveIntegerField(default=5)),
                ('completed', models.BooleanField(default=False)),
                ('interruption_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pomodoro Session',
                'verbose_name_plural': 'Pomodoro Sessions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', '-start_time'], name='core_pomodo_user_id_d0c38c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReactionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mean_rt', models.FloatField(help_text='Mean reaction time in milliseconds')),
                ('std_rt', models.FloatField(help_text='Standard deviation of reaction times')),
                ('variability', models.FloatField(help_text='Reaction time variability coefficient')),
                ('z_score', models.FloatField(help_text="Z-score relative to user's baseline")),
                ('valid_trials', models.PositiveIntegerField(default=0, help_text='Number of valid trials')),
                ('total_trials', models.PositiveIntegerField(default=0, help_text='Total number of trials')),
                ('false_starts', models.PositiveIntegerField(default=0, help_text='Number of false starts')),
                ('anticipations', models.PositiveIntegerField(default=0, help_text='Number of anticipatory responses')),
                ('drift_status', models.CharField(choices=[('stable', 'Stable'), ('warning', 'Warning'), ('drifting', 'Drifting'), ('critical', 'Critical')], default='stable', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction Session',
                'verbose_name_plural': 'Reaction Sessions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_reacti_user_id_f0b6f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('warning_level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('warning_message', models.TextField()),
                ('trigger_source', models.CharField(choices=[('reaction', 'Reaction Test'), ('eye', 'Eye Tracking'), ('hrv', 'HRV Sensor'), ('combined', 'Combined Analysis'), ('manual', 'Manual Trigger')], max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warning Log',
                'verbose_name_plural': 'Warning Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_warnin_user_id_186db1_idx'), models.Index(fields=['acknowledged'], name='core_warnin_acknowl_017579_idx')],
            },
        ),
    ]
