# Generated by Django 5.2.3 on 2026-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionsession',
            name='std_rt',
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='baseline_mean_at_time',
            field=models.FloatField(blank=True, help_text='Baseline mean when session was saved', null=True),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='baseline_sd_at_time',
            field=models.FloatField(blank=True, help_text='Baseline SD when session was saved', null=True),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='clean_reaction_times_json',
            field=models.TextField(blank=True, help_text='Clean valid reaction times only'),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='confidence_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('provisional', 'Provisional')], default='high', max_length=15),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='confidence_score',
            field=models.FloatField(default=1.0, help_text='Session quality/confidence (0-1)'),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='drift_level',
            field=models.CharField(choices=[('baseline_building', 'Baseline Building'), ('stable', 'Stable'), ('mild_drift', 'Mild Drift'), ('moderate_drift', 'Moderate Drift'), ('severe_drift', 'Severe Drift')], default='baseline_building', max_length=20),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='drift_score',
            field=models.FloatField(blank=True, help_text='Overall drift score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='percent_change_from_baseline',
            field=models.FloatField(blank=True, help_text='Change from baseline in percent', null=True),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='raw_reaction_times_json',
            field=models.TextField(blank=True, help_text='All reaction times (including flagged)'),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='sessions_in_baseline',
            field=models.PositiveIntegerField(default=0, help_text='Number of sessions used to establish baseline'),
        ),
        migrations.AddField(
            model_name='reactionsession',
            name='std_dev',
            field=models.FloatField(blank=True, help_text='Standard deviation of clean reaction times', null=True),
        ),
        migrations.AlterField(
            model_name='reactionsession',
            name='anticipations',
            field=models.PositiveIntegerField(default=0, help_text='RT < 100ms (too fast)'),
        ),
        migrations.AlterField(
            model_name='reactionsession',
            name='false_starts',
            field=models.PositiveIntegerField(default=0, help_text='Clicks before stimulus appeared'),
        ),
        migrations.AlterField(
            model_name='reactionsession',
            name='mean_rt',
            field=models.FloatField(blank=True, help_text='Mean reaction time in milliseconds (clean trials)', null=True),
        ),
        migrations.AlterField(
            model_name='reactionsession',
            name='total_trials',
            field=models.PositiveIntegerField(default=0, help_text='Total trials attempted'),
        ),
        migrations.AlterField(
            model_name='reactionsession',
            name='variability',
            field=models.FloatField(blank=True, help_text='Coefficient of variation (std_dev / mean)', null=True),
        ),
        migrations.AlterField(
            model_name='reactionsession',
            name='z_score',
            field=models.FloatField(blank=True, help_text="Z-score relative to user's personal baseline", null=True),
        ),
    ]
