# Generated by Django 5.2.3 on 2026-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_baseline_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyerecord',
            name='blink_duration',
        ),
        migrations.AddField(
            model_name='eyerecord',
            name='blink_count',
            field=models.PositiveIntegerField(default=0, help_text='Total blinks detected in session'),
        ),
        migrations.AddField(
            model_name='eyerecord',
            name='blink_duration_avg',
            field=models.FloatField(blank=True, help_text='Average blink duration in ms', null=True),
        ),
        migrations.AddField(
            model_name='eyerecord',
            name='ear',
            field=models.FloatField(blank=True, help_text='Eye Aspect Ratio (0.0-0.3)', null=True),
        ),
        migrations.AddField(
            model_name='eyerecord',
            name='ear_samples_json',
            field=models.TextField(blank=True, help_text='Recent EAR samples for trend analysis'),
        ),
        migrations.AddField(
            model_name='eyerecord',
            name='fatigue_flag',
            field=models.BooleanField(default=False, help_text='True if drowsiness detected'),
        ),
        migrations.AlterField(
            model_name='eyerecord',
            name='blink_rate',
            field=models.FloatField(blank=True, help_text='Blinks per minute', null=True),
        ),
        migrations.AlterField(
            model_name='eyerecord',
            name='eye_state',
            field=models.CharField(choices=[('normal', 'Normal'), ('fatigue', 'Fatigue'), ('eye_strain', 'Eye Strain'), ('drowsy', 'Drowsy'), ('looking_away', 'Looking Away')], default='normal', max_length=20),
        ),
    ]
