# Generated by Django 5.2.3 on 2026-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eye_module_phase3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrvrecord',
            name='ir_value',
            field=models.IntegerField(blank=True, help_text='Infrared sensor raw value from MAX30102', null=True),
        ),
        migrations.AlterField(
            model_name='hrvrecord',
            name='hrv_score',
            field=models.FloatField(blank=True, help_text='Computed HRV-based stress/fatigue score (0-100)', null=True),
        ),
    ]
