# Generated by Django 5.2.3 on 2026-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hrvrecord_ir_value_alter_hrvrecord_hrv_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrvrecord',
            name='stress_level',
            field=models.CharField(choices=[('relaxed', 'Relaxed'), ('normal', 'Normal'), ('mild_stress', 'Mild Stress'), ('moderate_stress', 'Moderate Stress'), ('high_stress', 'High Stress'), ('unstable', 'Unstable')], default='normal', max_length=20),
        ),
    ]
