# Generated by Django 5.2.3 on 2026-04-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hrvrecord_stress_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reaction_score', models.FloatField(blank=True, null=True)),
                ('eye_score', models.FloatField(blank=True, null=True)),
                ('hrv_score', models.FloatField(blank=True, null=True)),
                ('final_drift_score', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=20, null=True)),
                ('final_state', models.CharField(blank=True, max_length=30, null=True)),
                ('trigger_reaction_test', models.BooleanField(default=False)),
                ('intervention_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
