# Generated by Django 5.2.3 on 2026-04-17 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fusionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('within_study_hours', models.BooleanField(default=False)),
                ('eye_drift', models.BooleanField(default=False, help_text='Eye fatigue/drowsiness detected')),
                ('hrv_drift', models.BooleanField(default=False, help_text='HRV stress/abnormal detected')),
                ('suspected_drift', models.BooleanField(default=False, help_text='Both eye and HRV drift during study hours')),
                ('reaction_test_required', models.BooleanField(default=False)),
                ('reaction_test_completed', models.BooleanField(default=False, help_text='User completed the reaction test')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('suspected', 'Suspected Drift'), ('waiting_reaction', 'Waiting for Reaction Test'), ('confirmed_drift', 'Confirmed Drift'), ('false_alert', 'False Alert Avoided')], default='pending', max_length=20)),
                ('drift_confirmed', models.BooleanField(default=False, help_text='True if reaction confirmed drift vs baseline')),
                ('confirmation_reason', models.TextField(blank=True, help_text='Human-readable reason for validation result')),
                ('reaction_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_records', to='core.reactionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drift Validation',
                'verbose_name_plural': 'Drift Validations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_driftv_user_id_3ff7bb_idx'), models.Index(fields=['status'], name='core_driftv_status_e4d2ee_idx')],
            },
        ),
    ]
