# Generated by Django 5.2.3 on 2026-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_drift_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionrecord',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('suspected', 'Suspected'), ('confirmed_drift', 'Confirmed Drift'), ('false_alert', 'False Alert')], max_length=20, null=True),
        ),
    ]
