# Generated by Django 5.2.3 on 2026-04-25
# Phase 7: Warning and Intervention System

from django.db import migrations, models
import json


def convert_warning_levels(apps, schema_editor):
    """Convert old warning levels to new format."""
    WarningLog = apps.get_model('core', 'WarningLog')
    
    level_mapping = {
        'info': 'level_1',
        'low': 'level_1',
        'medium': 'level_2',
        'high': 'level_3',
        'critical': 'level_3',
    }
    
    for warning in WarningLog.objects.all():
        if warning.warning_level in level_mapping:
            warning.warning_level = level_mapping[warning.warning_level]
            warning.save()


def reverse_conversion(apps, schema_editor):
    """Reverse conversion if needed."""
    WarningLog = apps.get_model('core', 'WarningLog')
    
    level_mapping = {
        'level_1': 'low',
        'level_2': 'medium',
        'level_3': 'high',
        'level_4': 'critical',
    }
    
    for warning in WarningLog.objects.all():
        if warning.warning_level in level_mapping:
            warning.warning_level = level_mapping[warning.warning_level]
            warning.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_validation_status_to_fusion'),
    ]

    operations = [
        # Step 1: Add suggestions field with default
        migrations.AddField(
            model_name='warninglog',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        
        # Step 2: Alter warning_level choices
        migrations.AlterField(
            model_name='warninglog',
            name='warning_level',
            field=models.CharField(
                choices=[
                    ('level_1', 'Level 1 - Mild'),
                    ('level_2', 'Level 2 - Moderate'),
                    ('level_3', 'Level 3 - High'),
                    ('level_4', 'Level 4 - Chronic'),
                ],
                max_length=10
            ),
        ),
        
        # Step 3: Add index for warning_level
        migrations.AddIndex(
            model_name='warninglog',
            index=models.Index(fields=['warning_level'], name='warning_warn_level_idx'),
        ),
        
        # Step 4: Data migration - convert old levels to new
        migrations.RunPython(convert_warning_levels, reverse_conversion),
    ]