# Generated by Django 5.2.3 on 2026-04-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_phase7_warning_levels'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='warninglog',
            new_name='core_warnin_warning_e48fca_idx',
            old_name='warning_warn_level_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monitoring_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='warninglog',
            name='trigger_source',
            field=models.CharField(choices=[('reaction', 'Reaction Test'), ('eye', 'Eye Tracking'), ('hrv', 'HRV Sensor'), ('combined', 'Combined Analysis'), ('validation', 'Validation'), ('manual', 'Manual Trigger')], max_length=20),
        ),
    ]
